# Generated by Django 4.2.11 on 2026-05-05 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Plan')),
                ('dias_duracion', models.PositiveIntegerField(verbose_name='Días de Duración')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (VES)')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(editable=False, verbose_name='Fecha de Vencimiento')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='clients.client', verbose_name='Afiliado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
    ]
