# Generated by Django 4.2.11 on 2026-05-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_foto'),
        ('billing', '0003_exchangerate_remove_plan_precio_invoice_esta_impresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Dejar en blanco para acceso todo el día', null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='plan',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Dejar en blanco para acceso todo el día', null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no podrá ser comprado pero mantendrá el historial', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.client', verbose_name='Afiliado'),
        ),
    ]
