# Generated by Django 4.2.11 on 2026-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_client_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(choices=[('FIXED', 'Fijo'), ('FLEXIBLE', 'Flexible')], default='FIXED', max_length=10, verbose_name='Tipo de facturación'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dias_duracion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días de Duración'),
        ),
    ]
