# Generated by Django 4.2.11 on 2026-05-30 22:47

import apps.clients.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_task035_fixed_flexible_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0008_fixed_flexible_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa_monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Multa por morosidad (USD)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de facturación',
                'verbose_name_plural': 'Configuración de facturación',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='multa_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Multa (USD)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='multa_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Multa (VES)'),
        ),
        migrations.CreateModel(
            name='ClientBillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CUT_DATE_CHANGED', 'Cambio de fecha de corte'), ('SUBSCRIPTION_REACTIVATED', 'Reactivación de suscripción'), ('LATE_FEE_APPLIED', 'Multa aplicada'), ('LATE_FEE_WAIVED', 'Multa omitida')], max_length=32, verbose_name='Tipo')),
                ('payload', apps.clients.fields.SQLiteJSONField(blank=True, default=dict, verbose_name='Datos')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='clients.client', verbose_name='Afiliado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Evento de facturación',
                'verbose_name_plural': 'Eventos de facturación',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
