# Generated by Django 5.2.12 on 2026-06-30 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_invoiceline_class_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Anulada por'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='esta_anulada',
            field=models.BooleanField(default=False, verbose_name='¿Está Anulada?'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de anulación'),
        ),
    ]
