# Generated by Django 5.2.12 on 2026-07-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_reportemailsettings_gym_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbillingevent',
            name='event_type',
            field=models.CharField(choices=[('CUT_DATE_CHANGED', 'Cambio de fecha de corte'), ('SUBSCRIPTION_REACTIVATED', 'Reactivación de suscripción'), ('LATE_FEE_APPLIED', 'Multa aplicada'), ('LATE_FEE_WAIVED', 'Multa omitida'), ('MEMBERSHIP_DELETED', 'Membresía eliminada')], max_length=32, verbose_name='Tipo'),
        ),
    ]
