# Generated by Django 5.2.12 on 2026-07-27 12:47
#
# NOTA REVISADA: billing_corporategroup y billing_corporategroupmember fueron
# eliminadas manualmente porque la versión previa de esas tablas tenía un
# esquema distinto al requerido. corporate_group_id en billing_invoice YA existe.
# max_members en billing_plan YA existe.
# Por tanto:
#   - max_members: SeparateDatabaseAndState (solo estado ORM, columna ya existe)
#   - corporate_group_id en invoice: SeparateDatabaseAndState (ya existe)
#   - billing_corporategroup: CreateModel normal (tabla fue eliminada)
#   - billing_corporategroupmember: CreateModel normal (tabla fue eliminada)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_clientbillingevent_event_type'),
        ('clients', '0012_client_fixed_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # max_members ya existe en billing_plan — solo actualizar estado ORM
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='plan',
                    name='max_members',
                    field=models.PositiveIntegerField(
                        blank=True,
                        help_text='Solo para planes corporativos. Total de personas incluyendo el suscriptor principal.',
                        null=True,
                        verbose_name='Máximo de personas',
                    ),
                ),
            ],
            database_operations=[],
        ),
        # billing_type: ampliar choices para incluir CORPORATE
        migrations.AlterField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(
                choices=[('FIXED', 'Fijo'), ('FLEXIBLE', 'Flexible'), ('CORPORATE', 'Corporativo')],
                default='FIXED',
                max_length=10,
                verbose_name='Tipo de facturación',
            ),
        ),
        # CorporateGroup: tabla fue eliminada → crear de nuevo con esquema correcto
        migrations.CreateModel(
            name='CorporateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte_dia', models.PositiveSmallIntegerField(
                    help_text='Día del mes para renovación (1–31). Heredado del suscriptor o configurado al crear.',
                    verbose_name='Día de corte',
                )),
                ('status', models.CharField(
                    choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('DISSOLVED', 'Disuelto')],
                    db_index=True,
                    default='SUSPENDED',
                    max_length=16,
                    verbose_name='Estado',
                )),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('dissolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Disuelto el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_corporate_groups',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Creado por',
                )),
                ('dissolved_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='dissolved_corporate_groups',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Disuelto por',
                )),
                ('plan', models.ForeignKey(
                    limit_choices_to={'billing_type': 'CORPORATE'},
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='corporate_groups',
                    to='billing.plan',
                    verbose_name='Plan corporativo',
                )),
                ('subscriber', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='owned_corporate_groups',
                    to='clients.client',
                    verbose_name='Suscriptor principal',
                )),
            ],
            options={
                'verbose_name': 'Grupo corporativo',
                'verbose_name_plural': 'Grupos corporativos',
                'ordering': ['-created_at'],
            },
        ),
        # corporate_group_id en billing_invoice YA existe — solo estado ORM
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='invoice',
                    name='corporate_group',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='invoices',
                        to='billing.corporategroup',
                        verbose_name='Grupo corporativo',
                    ),
                ),
            ],
            database_operations=[],
        ),
        # CorporateGroupMember: tabla fue eliminada → crear de nuevo
        migrations.CreateModel(
            name='CorporateGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Ingresó el')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Salió el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo en el grupo')),
                ('added_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='added_corporate_members',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Agregado por',
                )),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='corporate_memberships',
                    to='clients.client',
                    verbose_name='Afiliado',
                )),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='members',
                    to='billing.corporategroup',
                    verbose_name='Grupo',
                )),
                ('removed_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='removed_corporate_members',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Retirado por',
                )),
            ],
            options={
                'verbose_name': 'Miembro de grupo corporativo',
                'verbose_name_plural': 'Miembros de grupos corporativos',
                'ordering': ['joined_at'],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_active', True)),
                        fields=('client',),
                        name='unique_active_corporate_member',
                    )
                ],
            },
        ),
    ]
