# Generated by Django 5.2.12 on 2026-09-02 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_invoice_payment_method_zelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='membership',
            name='fecha_corte_dia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día de corte con el que se registró esta membresía (1–31).', null=True, verbose_name='Día de corte (snapshot)'),
        ),
        migrations.AddField(
            model_name='membership',
            name='origen',
            field=models.CharField(choices=[('CHECKOUT', 'Cobro'), ('ADMIN', 'Acceso admin'), ('CORPORATE', 'Corporativo'), ('CORPORATE_JOIN', 'Alta corporativa'), ('UNKNOWN', 'Histórico')], default='UNKNOWN', max_length=16, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('QUEUED', 'Encolada'), ('EXPIRED', 'Vencida'), ('VOIDED', 'Anulada'), ('CLOSED', 'Cerrada')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientbillingevent',
            name='event_type',
            field=models.CharField(choices=[('CUT_DATE_CHANGED', 'Cambio de fecha de corte'), ('SUBSCRIPTION_REACTIVATED', 'Reactivación de suscripción'), ('LATE_FEE_APPLIED', 'Multa aplicada'), ('LATE_FEE_WAIVED', 'Multa omitida'), ('MEMBERSHIP_DELETED', 'Membresía eliminada'), ('ADMIN_ACCESS_GRANTED', 'Acceso administrativo asignado'), ('INVOICE_VOIDED', 'Factura anulada'), ('MEMBERSHIP_SOFT_CLOSED', 'Membresía cerrada sin borrar'), ('MEMBERSHIP_VOIDED', 'Membresía anulada')], max_length=32, verbose_name='Tipo'),
        ),
    ]
