# Generated by Django 4.2.11 on 2026-09-11 17:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_membership_history_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='inscripcion_monto_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Inscripción (USD)'),
        ),
        migrations.AlterField(
            model_name='clientbillingevent',
            name='event_type',
            field=models.CharField(choices=[('CUT_DATE_CHANGED', 'Cambio de fecha de corte'), ('SUBSCRIPTION_REACTIVATED', 'Reactivación de suscripción'), ('LATE_FEE_APPLIED', 'Multa aplicada'), ('LATE_FEE_WAIVED', 'Multa omitida'), ('ENROLLMENT_FEE_APPLIED', 'Inscripción cobrada'), ('ENROLLMENT_FEE_WAIVED', 'Inscripción omitida'), ('MEMBERSHIP_DELETED', 'Membresía eliminada'), ('ADMIN_ACCESS_GRANTED', 'Acceso administrativo asignado'), ('INVOICE_VOIDED', 'Factura anulada'), ('MEMBERSHIP_SOFT_CLOSED', 'Membresía cerrada sin borrar'), ('MEMBERSHIP_VOIDED', 'Membresía anulada')], max_length=32, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_kind',
            field=models.CharField(choices=[('MEMBERSHIP', 'Membresía'), ('PRODUCT', 'Producto o servicio'), ('LATE_FEE', 'Multa'), ('ENROLLMENT_FEE', 'Inscripción'), ('CLASS', 'Clase')], max_length=16, verbose_name='Tipo de línea'),
        ),
    ]
