from django.urls import path
from .views import (
    ChargeCheckoutView,
    SaleItemListView,
    SaleItemCreateView,
    SaleItemUpdateView,
    SaleItemDeleteView,
    RenewPlanView,
    ChangeCutDateView,
    PaymentPeriodPreviewView,
    PaymentSuccessView,
    PlanListView,
    PlanCreateView,
    PlanUpdateView,
    PlanDeleteView,
    MembershipDeleteView,
    DeleteMembershipActionView,
    ExchangeRateUpdateView,
    InvoiceListView,
    InvoiceDetailView,
    InvoiceTicketPreviewView,
    PrintInvoiceActionView,
    InvoiceDeleteView,
    VoidInvoiceView,
    UnbindFixedPlanView,
    GlobalPersonSearchView,
    PersonProfileSearchView,
    ReportView,
    ReportSendView,
    FiscalReportPrintView,
    FiscalReportView,
    SummaryReportView,
    # Corporate
    CorporateGroupListView,
    CorporateGroupCreateView,
    CorporateGroupDetailView,
    CorporateGroupAddMemberView,
    CorporateGroupRemoveMemberView,
    CorporateGroupDissolveView,
    CorporateGroupPreviewResetView,
)

app_name = 'billing'

urlpatterns = [
    path('cobro/<str:codigo_afiliado>/', ChargeCheckoutView.as_view(), name='charge_checkout'),
    path('buscar-persona/', GlobalPersonSearchView.as_view(), name='person_search'),
    path('buscar-perfil/', PersonProfileSearchView.as_view(), name='person_profile_search'),
    path('renovar/<str:codigo_afiliado>/', RenewPlanView.as_view(), name='renew_plan'),
    path('preview-cobro/<str:codigo_afiliado>/', PaymentPeriodPreviewView.as_view(), name='payment_preview'),
    path('cobro-exito/<int:pk>/', PaymentSuccessView.as_view(), name='payment_success'),
    path('corte/<str:codigo_afiliado>/', ChangeCutDateView.as_view(), name='change_cut_date'),
    path('productos/', SaleItemListView.as_view(), name='product_list'),
    path('productos/nuevo/', SaleItemCreateView.as_view(), name='product_create'),
    path('productos/<int:pk>/editar/', SaleItemUpdateView.as_view(), name='product_update'),
    path('productos/<int:pk>/eliminar/', SaleItemDeleteView.as_view(), name='product_delete'),
    path('planes/', PlanListView.as_view(), name='plan_list'),
    path('planes/nuevo/', PlanCreateView.as_view(), name='plan_create'),
    path('planes/editar/<int:pk>/', PlanUpdateView.as_view(), name='plan_update'),
    path('planes/borrar/<int:pk>/', PlanDeleteView.as_view(), name='plan_delete'),
    path('membresia/eliminar/<int:pk>/', MembershipDeleteView.as_view(), name='membership_delete'),
    path('membresia/eliminar-accion/<int:pk>/', DeleteMembershipActionView.as_view(), name='delete_membership_action'),
    path('tasa/actualizar/', ExchangeRateUpdateView.as_view(), name='update_rate'),
    path('facturas/', InvoiceListView.as_view(), name='invoice_list'),
    path('facturas/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail'),
    path('facturas/<int:pk>/preview-ticket/', InvoiceTicketPreviewView.as_view(), name='invoice_ticket_preview'),
    path('facturas/<int:pk>/imprimir/', PrintInvoiceActionView.as_view(), name='print_invoice'),
    path('facturas/<int:pk>/anular/', VoidInvoiceView.as_view(), name='invoice_void'),
    path('facturas/<int:pk>/eliminar/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    # DEPRECATED: reemplazado por cierre-fiscal/ y resumen/ (TASK-110)
    path('reportes/', ReportView.as_view(), name='report'),
    path('cierre-fiscal/', FiscalReportView.as_view(), name='fiscal_report'),
    path('resumen/', SummaryReportView.as_view(), name='summary_report'),
    path('reportes/enviar/', ReportSendView.as_view(), name='report_send'),
    path('cobro/<str:codigo_afiliado>/desvincular-plan/', UnbindFixedPlanView.as_view(), name='unbind_fixed_plan'),
    path('reportes/fiscal/', FiscalReportPrintView.as_view(), name='fiscal_report_print'),

    # ---- Grupos Corporativos ----
    path('corporativo/', CorporateGroupListView.as_view(), name='corporate_group_list'),
    path('corporativo/nuevo/', CorporateGroupCreateView.as_view(), name='corporate_group_create'),
    path('corporativo/preview-reset/', CorporateGroupPreviewResetView.as_view(), name='corporate_preview_reset'),
    path('corporativo/<int:pk>/', CorporateGroupDetailView.as_view(), name='corporate_group_detail'),
    path('corporativo/<int:pk>/agregar-miembro/', CorporateGroupAddMemberView.as_view(), name='corporate_group_add_member'),
    path('corporativo/<int:pk>/quitar-miembro/', CorporateGroupRemoveMemberView.as_view(), name='corporate_group_remove_member'),
    path('corporativo/<int:pk>/disolver/', CorporateGroupDissolveView.as_view(), name='corporate_group_dissolve'),
]
