# Generated by Django 4.2.11 on 2026-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_sqlitejsonfield_face_id_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fecha_corte_dia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para renovación de plan fijo (1-31). Se asigna en el primer pago fijo.', null=True, verbose_name='Día de corte (suscripción fija)'),
        ),
    ]
