# Generated by Django 5.2.12 on 2026-07-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_guest_pass_nullable_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blocking_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del bloqueo'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Si se activa, el afiliado no podrá ingresar aunque tenga membresía activa.', verbose_name='Bloqueado'),
        ),
    ]
