# Generated by Django 4.2.11 on 2026-07-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_clientbillingevent_event_type'),
        ('clients', '0011_client_blocking_reason_client_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fixed_plan',
            field=models.ForeignKey(blank=True, help_text='Plan fijo asociado al afiliado. Se asigna al confirmar el primer cobro de un plan fijo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan', verbose_name='Plan fijo vinculado'),
        ),
    ]
