# Generated by Django 4.2.11 on 2026-08-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_fixed_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='person_category',
            field=models.CharField(choices=[('MEMBER', 'Afiliado'), ('EMPLOYEE', 'Empleado'), ('TRAINER', 'Entrenador'), ('GUEST', 'Invitado'), ('PARTNER', 'Socio')], db_index=True, default='MEMBER', max_length=10, verbose_name='Categoría'),
        ),
    ]
