# Generated by Django 4.2.11 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_alter_client_person_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="profile_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Nota permanente visible en el perfil del afiliado o invitado.",
                verbose_name="Nota de perfil",
            ),
        ),
    ]
