# Generated by Django 4.2.11 on 2026-09-18 12:54

import apps.clients.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_profile_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='best_embeddings',
            field=apps.clients.fields.SQLiteJSONField(blank=True, help_text='Embedding auxiliar promovido de los últimos accesos de alta confianza.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='best_embeddings_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de consistencia del best_embeddings (menor = mejor)'),
        ),
        migrations.CreateModel(
            name='ClientAdaptiveEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', apps.clients.fields.SQLiteJSONField()),
                ('margin', models.FloatField(blank=True, null=True, verbose_name='Margin del acceso que lo generó')),
                ('best_distance', models.FloatField(verbose_name='Distancia del match que lo generó')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_embeddings', to='clients.client', verbose_name='Afiliado')),
            ],
            options={
                'verbose_name': 'Embedding adaptativo',
                'verbose_name_plural': 'Embeddings adaptativos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='clients_cli_client__1b4c9e_idx')],
            },
        ),
    ]
