# Generated by Django 5.2.12 on 2026-06-30 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_manual_turnstile_access'),
        ('clients', '0010_guest_pass_nullable_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='clients.client', verbose_name='Afiliado'),
        ),
    ]
