# Generated by Django 5.2.12 on 2026-07-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_accesslog_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualturnstileaccess',
            name='reason',
            field=models.CharField(choices=[('biometric_failure', 'Falla biométrica'), ('admin_authorization', 'Autorización administrativa'), ('enrollment_pending', 'Enrolamiento pendiente'), ('guest_or_vendor', 'Invitado o proveedor'), ('emergency', 'Emergencia'), ('unspecified', 'Sin razón especificada'), ('other', 'Otra')], max_length=40, verbose_name='Razón'),
        ),
    ]
