# Generated by Django 5.2.12 on 2026-07-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_manualturnstileaccess_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_access_cooldown_seconds', models.PositiveIntegerField(default=0, help_text='Tiempo mínimo entre accesos biométricos concedidos a la misma persona. 0 = desactivado.', verbose_name='Enfriamiento post-acceso (segundos)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de acceso',
                'verbose_name_plural': 'Configuración de acceso',
            },
        ),
    ]
